apiVersion: apps/v1
kind: Deployment
metadata:
  name: rirdarir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rirdarir
  template:
    metadata:
      labels:
        app: rirdarir
    spec:
      containers:
      - image: okteto.dev/rirdarir:latest
        name: rirdarir
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ec0aa6ad-4506-4b24-b6e6-0991358f653e"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "ec0aa6ad-4506-4b24-b6e6-0991358f653e"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
